import 'dotenv/config';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Pool } from 'pg';
import { addEvent, recordDbRead, recordDbWrite } from './metrics.js';
import { notFound, serviceUnavailable } from './errors.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_FILE = path.join(__dirname, 'data', 'students.json');
const DATABASE_URL = process.env.DATABASE_URL;
const DATABASE_SSL = process.env.DATABASE_SSL !== 'false';
const ALLOW_JSON_FALLBACK = !DATABASE_URL || process.env.DATABASE_ALLOW_JSON_FALLBACK === 'true';
const POSTGRES_RETRY_INTERVAL_MS = 10_000;

let state = JSON.parse(fs.readFileSync(DATA_FILE, 'utf-8'));
let pool = null;
let postgresReady = false;
let postgresInitPromise = null;
let lastPostgresError = null;
let lastPostgresAttemptAt = 0;

function clone(value) {
  return structuredClone(value);
}

function now() {
  return Date.now();
}

function databaseHost() {
  if (!DATABASE_URL) return null;

  try {
    return new URL(DATABASE_URL).host;
  } catch {
    return 'configurado';
  }
}

function ensureLocalFallback() {
  if (ALLOW_JSON_FALLBACK) return;

  throw serviceUnavailable(
    'Supabase/Postgres indisponivel. Ajuste DATABASE_URL para a connection string pooler do Supabase ou habilite DATABASE_ALLOW_JSON_FALLBACK=true para usar JSON local.'
  );
}

function runLocalFallback(operation) {
  ensureLocalFallback();
  return operation();
}

function studentFromRow(row) {
  return {
    id: Number(row.id),
    name: row.name,
    email: row.email,
    course: row.course,
    period: Number(row.period),
    gradeAverage: Number(row.grade_average),
    cacheEnabled: row.cache_enabled !== false
  };
}

function studentFromState(student) {
  return {
    ...clone(student),
    cacheEnabled: student.cacheEnabled !== false
  };
}

function createPool() {
  return new Pool({
    connectionString: DATABASE_URL,
    ssl: DATABASE_SSL ? { rejectUnauthorized: false } : false
  });
}

function jitter(baseMs) {
  return baseMs + Math.floor(Math.random() * 45);
}

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function simulateDatabaseLatency(kind) {
  await delay(jitter(kind === 'read' ? 125 : 85));
}

function persist() {
  fs.writeFileSync(DATA_FILE, `${JSON.stringify(state, null, 2)}\n`);
}

async function seedPostgres(client) {
  const countResult = await client.query('select count(*)::int as count from students');
  if (countResult.rows[0].count > 0) return;

  for (const student of state.students) {
    await client.query(
      `insert into students (id, name, email, course, period, grade_average, cache_enabled)
       values ($1, $2, $3, $4, $5, $6, $7)
       on conflict (id) do nothing`,
      [
        student.id,
        student.name,
        student.email,
        student.course,
        student.period,
        student.gradeAverage,
        student.cacheEnabled !== false
      ]
    );
  }

  await client.query(`
    select setval(
      pg_get_serial_sequence('students', 'id'),
      coalesce((select max(id) from students), 1)
    )
  `);
}

async function initializePostgres(client) {
  await client.query(`
    create table if not exists students (
      id integer generated by default as identity primary key,
      name text not null,
      email text not null,
      course text not null,
      period integer not null check (period between 1 and 12),
      grade_average numeric(3, 1) not null check (grade_average between 0 and 10),
      cache_enabled boolean not null default true,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    )
  `);

  await client.query(`
    alter table students
    add column if not exists cache_enabled boolean not null default true
  `);

  await seedPostgres(client);
}

async function getPostgresPool() {
  if (!DATABASE_URL) return null;
  if (postgresReady && pool) return pool;
  if (postgresInitPromise) return postgresInitPromise;
  if (lastPostgresError && now() - lastPostgresAttemptAt < POSTGRES_RETRY_INTERVAL_MS) return null;

  lastPostgresAttemptAt = now();
  if (!pool) pool = createPool();

  postgresInitPromise = (async () => {
    const client = await pool.connect();

    try {
      await initializePostgres(client);
      postgresReady = true;
      lastPostgresError = null;
      addEvent('database', `Postgres conectado: ${databaseHost()}`);
      return pool;
    } finally {
      client.release();
    }
  })()
    .catch((error) => {
      postgresReady = false;
      lastPostgresError = error.message;
      addEvent(
        'database-error',
        ALLOW_JSON_FALLBACK
          ? 'Postgres indisponivel; usando JSON local'
          : 'Postgres indisponivel; fallback JSON bloqueado',
        {
          host: databaseHost(),
          message: error.message
        }
      );
      return null;
    })
    .finally(() => {
      postgresInitPromise = null;
    });

  return postgresInitPromise;
}

export function getDatabaseState() {
  return {
    backend: postgresReady ? 'postgres' : (ALLOW_JSON_FALLBACK ? 'json' : 'unavailable'),
    postgres: {
      configured: Boolean(DATABASE_URL),
      connected: postgresReady,
      host: databaseHost(),
      lastError: lastPostgresError
    },
    fallback: {
      jsonEnabled: ALLOW_JSON_FALLBACK
    }
  };
}

function peekLocalFirstStudentId() {
  return state.students[0]?.id ?? null;
}

async function findLocalAllStudents() {
  recordDbRead('listar alunos');
  await simulateDatabaseLatency('read');
  return state.students.map(studentFromState);
}

async function findLocalStudentById(id) {
  recordDbRead(`aluno ${id}`);
  await simulateDatabaseLatency('read');
  const student = state.students.find((item) => item.id === id);
  if (!student) throw notFound('Aluno nao encontrado.');
  return studentFromState(student);
}

async function createLocalStudent(student) {
  recordDbWrite('cadastrar aluno');
  await simulateDatabaseLatency('write');

  const created = {
    ...student,
    id: state.nextId,
    cacheEnabled: student.cacheEnabled !== false
  };

  state = {
    nextId: state.nextId + 1,
    students: [...state.students, created]
  };

  persist();
  return studentFromState(created);
}

async function replaceLocalStudent(id, student) {
  recordDbWrite(`substituir aluno ${id}`);
  await simulateDatabaseLatency('write');

  let updated = null;
  state = {
    ...state,
    students: state.students.map((item) => {
      if (item.id !== id) return item;
      updated = { ...student, id, cacheEnabled: student.cacheEnabled !== false };
      return updated;
    })
  };

  if (!updated) throw notFound('Aluno nao encontrado.');
  persist();
  return studentFromState(updated);
}

async function patchLocalStudent(id, patch) {
  recordDbWrite(`atualizar aluno ${id}`);
  await simulateDatabaseLatency('write');

  let updated = null;
  state = {
    ...state,
    students: state.students.map((item) => {
      if (item.id !== id) return item;
      updated = { ...item, ...patch, id };
      return updated;
    })
  };

  if (!updated) throw notFound('Aluno nao encontrado.');
  persist();
  return studentFromState(updated);
}

async function removeLocalStudent(id) {
  recordDbWrite(`remover aluno ${id}`);
  await simulateDatabaseLatency('write');

  const student = state.students.find((item) => item.id === id);
  if (!student) throw notFound('Aluno nao encontrado.');

  state = {
    ...state,
    students: state.students.filter((item) => item.id !== id)
  };

  persist();
  return studentFromState(student);
}

export async function peekFirstStudentId() {
  const postgres = await getPostgresPool();

  if (!postgres) return runLocalFallback(peekLocalFirstStudentId);

  const result = await postgres.query('select id from students order by id limit 1');
  return result.rows[0]?.id ?? null;
}

export async function findAllStudents() {
  const postgres = await getPostgresPool();

  if (!postgres) return runLocalFallback(findLocalAllStudents);

  recordDbRead('listar alunos no Postgres');
  const result = await postgres.query(`
    select id, name, email, course, period, grade_average, cache_enabled
    from students
    order by id
  `);

  return result.rows.map(studentFromRow);
}

export async function findStudentById(id) {
  const postgres = await getPostgresPool();

  if (!postgres) return runLocalFallback(() => findLocalStudentById(id));

  recordDbRead(`aluno ${id} no Postgres`);
  const result = await postgres.query(
    `select id, name, email, course, period, grade_average, cache_enabled
     from students
     where id = $1`,
    [id]
  );

  if (!result.rows.length) throw notFound('Aluno nao encontrado.');
  return studentFromRow(result.rows[0]);
}

export async function createStudent(student) {
  const postgres = await getPostgresPool();

  if (!postgres) return runLocalFallback(() => createLocalStudent(student));

  recordDbWrite('cadastrar aluno no Postgres');
  const result = await postgres.query(
    `insert into students (name, email, course, period, grade_average, cache_enabled)
     values ($1, $2, $3, $4, $5, $6)
     returning id, name, email, course, period, grade_average, cache_enabled`,
    [student.name, student.email, student.course, student.period, student.gradeAverage, student.cacheEnabled !== false]
  );

  return studentFromRow(result.rows[0]);
}

export async function replaceStudent(id, student) {
  const postgres = await getPostgresPool();

  if (!postgres) return runLocalFallback(() => replaceLocalStudent(id, student));

  recordDbWrite(`substituir aluno ${id} no Postgres`);
  const result = await postgres.query(
    `update students
     set name = $2,
         email = $3,
         course = $4,
         period = $5,
         grade_average = $6,
         cache_enabled = $7,
         updated_at = now()
     where id = $1
     returning id, name, email, course, period, grade_average, cache_enabled`,
    [id, student.name, student.email, student.course, student.period, student.gradeAverage, student.cacheEnabled !== false]
  );

  if (!result.rows.length) throw notFound('Aluno nao encontrado.');
  return studentFromRow(result.rows[0]);
}

export async function patchStudent(id, patch) {
  const postgres = await getPostgresPool();

  if (!postgres) return runLocalFallback(() => patchLocalStudent(id, patch));

  const fieldMap = {
    name: 'name',
    email: 'email',
    course: 'course',
    period: 'period',
    gradeAverage: 'grade_average',
    cacheEnabled: 'cache_enabled'
  };
  const values = [id];
  const assignments = [];

  for (const [field, value] of Object.entries(patch)) {
    const column = fieldMap[field];
    if (!column) continue;
    values.push(value);
    assignments.push(`${column} = $${values.length}`);
  }

  recordDbWrite(`atualizar aluno ${id} no Postgres`);
  const result = await postgres.query(
    `update students
     set ${assignments.join(', ')}, updated_at = now()
     where id = $1
     returning id, name, email, course, period, grade_average, cache_enabled`,
    values
  );

  if (!result.rows.length) throw notFound('Aluno nao encontrado.');
  return studentFromRow(result.rows[0]);
}

export async function removeStudent(id) {
  const postgres = await getPostgresPool();

  if (!postgres) return runLocalFallback(() => removeLocalStudent(id));

  recordDbWrite(`remover aluno ${id} no Postgres`);
  const result = await postgres.query(
    `delete from students
     where id = $1
     returning id, name, email, course, period, grade_average, cache_enabled`,
    [id]
  );

  if (!result.rows.length) throw notFound('Aluno nao encontrado.');
  return studentFromRow(result.rows[0]);
}
